### ISSUE TITLE
Search binaries in /usr/bin

### ISSUE THREAD

**Issue by Motsyo** [drigler/DeroGUIWallet#1]
Hi!

It is very necessary to add a functionality so that the program finds binary files not only in "Resources/bin", but also in "/usr/bin".

This is necessary for add your application to the official ALT Linux repository.

Tnx!

**Comment by drigler** [comment]
Hi, tnx for pointing out, but this is a temporary project meant to be replaced by official GUI wallet from original dero devs. So there is no need to add this program to ALT Linux.
