### ISSUE TITLE
Wallet 

### ISSUE THREAD

**Issue by shaners1** [drigler/DeroGUIWallet#2]
Hello, 

All of a sudden this morning my wallet fell out of sync and is stuck at Synchronizing... 54082/550**.
My balance is also showing incorrectly (wrong amount). Is there anything I can do to fix this? I have waited all day to see if the Sync would complete on its own.

Sorry in advance for the noob question!

![image](https://user-images.githubusercontent.com/34141110/38170543-6d9c3866-3556-11e8-94db-67a78ca4f554.png)

![image](https://user-images.githubusercontent.com/34141110/38170548-82404d66-3556-11e8-9949-1a9de037e920.png)

Thanks,
Shaners

**Comment by drigler** [comment]
Hi Shaners,

you will need to move to new golang version of Dero. Download new binaries from official repo http://seeds.dero.io/alpha/

Run daemon and wait untill it's synced. Then restore your wallet using seed words from the old wallet.

There is no GUI wallet that support's GO version of daemon yet, so you will need to use  CLI version. But it's easy to use as it's menu based.

Let me know if u have any issues, I will be glad to help you.

Denis
